name: Design pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t my-image:latest .

      - name: Run Docker container
        # TODO: enable this when we have set the secrets
        #run: docker run -e API_KEY=${{ secrets.RXN_API_KEY }} -e PROJ_ID=${{ secrets.RXN_PROJ_ID }} my-image:latest
        run: docker run -e API_KEY=WRONG -e PROJ_ID=WRONG my-image:latest
